---
abstract: 'kd-Tree implementation on top of Math::Vector::Real'
author:
  - 'Salvador Fandiño <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Vector-Real-kdTree
no_index:
  directory:
    - t
    - inc
requires:
  Math::Vector::Real: 0.06
  Sort::Key::Top: 0.06
version: 0.09
